### ISSUE TITLE
Problems with register/log in

### ISSUE THREAD

**Issue by Radu-Antonio** [BiancaGabriela06/ProjectMDS#1]
I tried to register an *already existing account* (forgot I already have one) and for some reason in the database we got 2 users with the same credentials. 

Please fix this @BiancaGabriela06.

**Comment by BiancaGabriela06** [comment]
Sorry, mate! I fixed it and now if you are registering the backend verify if the user is found in database.

**Comment by Radu-Antonio** [comment]
Yes now it works. 

Thx 👍
